### ISSUE TITLE
What should the specific conditions be to alert when something goes wrong? Like for the long pause, how long should the pause be (e.g. bathroom break)?

### ISSUE THREAD

**Issue by getDolla** [wxiang54/DiCiWi-SolRoute#1]

**Comment by wxiang54** [comment]
We could make it customizable to the user, but we'll most likely set standards to start out.

**Comment by yhzhan** [comment]
Even if it's a bathroom break, we should still send an alert to be sure, unless it's something that will be happening on the daily.
